#SPDX-License-Identifier: MIT-0
---
# tasks file for k3s-worker
- name: download k3s script
  get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Get fresh node token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  delegate_to: "{{ groups['masters'][0] }}"
  register: node_token_raw


- name: Set node token fact
  set_fact:
    k3s_node_token: "{{ node_token_raw.content | b64decode | trim }}"

- name: Install k3s agent
  shell: |
    export INSTALL_K3S_EXEC="agent --with-node-id"
    export K3S_URL="https://{{ hostvars[groups['masters'][0]]['ansible_host'] }}:{{ api_port }}"
    export K3S_TOKEN="{{ k3s_node_token }}"
    sh /tmp/k3s-install.sh
  args:
    creates: /usr/local/bin/k3s
  async: 300
  poll: 10
  register: k3s_install_result

- name: Display installation result
  debug:
    var: k3s_install_result.stdout_lines
  when: k3s_install_result.stdout_lines is defined

- name: Wait for k3s-agent service to be ready
  systemd:
    name: k3s-agent
    state: started
    enabled: yes
  retries: 5
  delay: 10

- name: Verify agent is connecting to master
  shell: systemctl status k3s-agent --no-pager
  register: agent_status
  
- name: Show agent status
  debug:
    var: agent_status.stdout_lines
